config {
  type: "operations", //  comments blabla
 
}


-- The rest of a SQLX file contains your SELECT statement used to create the table.

TRUNCATE TABLE `dataformtraining2024.prepared_ua.staging_2`;
INSERT INTO `dataformtraining2024.prepared_ua.staging_2`
SELECT * 
  FROM `test-serge-1995.raw_ua.staging_2`;
  
CREATE TABLE `dataformtraining2024.prepared_ua.staging_1_ghost`

--,("Christopher", "Nolan", "Oppenheimer")


-- select "Hello Serge"