config {
  type: "incremental", //  comments blabla
  schema: "prepared_ua",
  uniqueKey: ["id"]
//  dependents : ["sql_enterprise_ua_update_final_table"]
 
}
--pre_operations {
--   ${when(incremental(),`TRUNCATE TABLE ${self()}`)}
--
--}


-- The rest of a SQLX file contains your SELECT statement used to create the table.

SELECT * 
  FROM `test-serge-1995.raw_ua.staging_1`

${when(incremental(),`WHERE last_name NOT IN (SELECT last_name FROM ${self()})`)}

